### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [Junparkk/image_community#2]
- 과제하시느라 고생 많으셨습니다 😄

- 좋아요 기능을 하시다가 그만두신 흔적들이 보이네요. 처음에 구현시에 많이 이해가 안갈수 있습니다 괜찮아요 😄 우선 이럴 경우에 기능을 구현하기전에 좋아요 기능이 어떤 순서로 실행되는지를 혼자 정리해보시고 구현에 도전해보시면 도움이 될거에요.

- 우선 firebase에 post,like 테이블을 생성하게 되겠죠? 그리고 각 유저별로 어떤 게시물에 좋아요를 눌렀는지도 알아야하겠죠, 여기서 like 테이블에 각 유저아이디별로 그 안에 좋아요를 누른 post_id들을 담게됩니다. 그후에 like 테이블에서 로그인한 유저의 uid or user_id를 비교해서 해당 유저가 좋아요를 누른 post_id들을 가져오면 됩니다. 그 후에 postlist 컴포넌트가 렌더링될때 로그인한 유저가 좋아요를 누른 post_id들과 하나하나의 post의 post_id를 눌렀는지 아닌지에 대한 여부를 비교해보고 좋아요 표시를 해주게되고 유저는 본인이 좋아요를 누른 게시물들을 알수있게 됩니다. 

- 물론 위 내용도 아직 어색해서 잘 이해가 안가실수도 있어요! 하지만 제가 말씀드리고자 했던건 어떤 원리로 이게 가능하지를 혼자 생각해보고 정리해보면서 그 후에 코드를 구현해 나가보시는것도 좋은 경험치가 되실겁니다. 😎

**Comment by Junparkk** [comment]
감사합니다 이해하는데 많은 도움이 되었습니다
